### ISSUE TITLE
Remove "animation-frame" dependency

### ISSUE THREAD

**Issue by stevenvachon** [davesnx/scrollto-with-animation#28]
Polyfills/shims should be added by the consumer.

**Comment by davesnx** [comment]
Hey @stevenvachon 

Same as the other issue, I prefer developer experience and easy to plug and play over correctness. animation-frame isn't an easy polyfill to find to trust. 

It's true, that generally polyfills should be added by the client much APIs, for many many reasons. But I prefer to release a polyfill-bundled approach since there would be many people using this and not reading a warning on the readme that highly recommends using a polyfill.

Thanks for reporting the issue
